kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nutanix-volume
provisioner: csi.nutanix.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: ntnx-secret
  csi.storage.k8s.io/provisioner-secret-namespace: openshift-cluster-csi-drivers
  csi.storage.k8s.io/node-publish-secret-name: ntnx-secret
  csi.storage.k8s.io/node-publish-secret-namespace: openshift-cluster-csi-drivers
  csi.storage.k8s.io/controller-expand-secret-name: ntnx-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: openshift-cluster-csi-drivers
  csi.storage.k8s.io/fstype: ext4
  storageContainer: default-container-77164748348465
  storageType: NutanixVolumes
  #description: "description added to each storage object created by the driver"
  #isSegmentedIscsiNetwork: "false"
  #whitelistIPMode: ENABLED
  #chapAuth: ENABLED
  #isLVMVolume: "false"
  #numLVMDisks: 4
allowVolumeExpansion: true
reclaimPolicy: Delete
